### ISSUE TITLE
negative

### ISSUE THREAD

**Issue by syahdeini** [emsansone/GAN#1]
Hey if I may ask, why do you put negative inside the reduce_mean in this line
https://github.com/emsansone/GAN/blob/5747f1e135deff2f7f49a93738c28e3dfd10f5b9/gan.py#L90

**Comment by emsansone** [comment]
Hi,

Because I perform a minimization (max J = min -J )

Is it clear?

Il giorno 12 mag 2018, alle ore 21:15, Aldy syahdeini <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hey if I may ask, why do you put negative inside the reduce_mean in this line
https://github.com/emsansone/GAN/blob/5747f1e135deff2f7f49a93738c28e3dfd10f5b9/gan.py#L90

**Comment by syahdeini** [comment]
Yes thanks
